# Generated by Django 4.2 on 2023-06-16 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0003_remove_subscription_end_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
