# Generated by Django 4.2 on 2023-06-16 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0005_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
