# Generated by Django 4.2.2 on 2023-06-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0008_alter_subscription_address_line_1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="address_line_1",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="admin_area_2",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="capture_amount_currency_code",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="capture_amount_value",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="capture_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="capture_status",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="country_code",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="dispute_categories",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="final_capture",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="intent",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="links_href",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="links_method",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="links_rel",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payee_email_address",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payee_merchant_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payer_country_code",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payer_email_address",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payer_given_name",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payer_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="payer_surname",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="reference_id",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="seller_protection_status",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="update_time",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="currency_code",
            field=models.CharField(blank=True, default="USD", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                blank=True, default="COMPLETED", max_length=255, null=True
            ),
        ),
    ]
