# Generated by Django 4.2.2 on 2023-06-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registration", "0009_remove_subscription_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
