# Generated by Django 4.2.2 on 2023-10-15 16:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_planType', models.CharField(default='Month', max_length=30)),
                ('payID', models.CharField(blank=True, default=0, max_length=255)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('startTime', models.DateTimeField(default=datetime.datetime(2023, 10, 15, 16, 51, 49, 734228))),
                ('endTime', models.DateTimeField(default=datetime.datetime(2023, 10, 15, 16, 51, 49, 734609))),
                ('is_active', models.BooleanField(default=False)),
                ('nameTelegram', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planType', models.CharField(choices=[('Month', 'Month')], max_length=50)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='create_subActive',
            fields=[
                ('subactive_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram.subactive')),
            ],
            bases=('telegram.subactive', django.views.generic.base.View),
        ),
        migrations.CreateModel(
            name='telegramView',
            fields=[
                ('telegramgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='telegram.telegramgroup')),
            ],
            bases=('telegram.telegramgroup', django.views.generic.base.View),
        ),
    ]
